auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: LI, Yu from 1981
url: http://liyu1981.github.io
feed: /atom.xml
author_info: <a href="http://liyu1981.github.io/">LI,Yu</a>
